### ISSUE TITLE
apply rcs vs `insert-file-contents`

### ISSUE THREAD

**Issue by aaronjensen** [dominikh/langfmt.el#2]
Hi there, it does seem like you're not working on this at the moment, but I was curious if when you originally wrote the gofmt hook if you had tried `insert-file-contents` rather than diff + applying an rcs patch. I've just moved https://github.com/aaronjensen/eslintd-fix from using a copy of your code to using `insert-file-contents` and it seems to work the same and pretty well. I'm curious if there were any dragons there or if it just wasn't available/known at the time you originally wrote gofmt.

By the way, thank you for gofmt, without it I wouldn't have had the foundation necessary to build eslintd-fix.

Thanks!

**Comment by dominikh** [comment]
The short answer is that I wasn't aware of the `REPLACE` argument of `insert-file-contents`. The diff+apply approach was chosen to maintain the cursor position and a smaller undo history, but insert-file-contents promises the same. I'll have to look into that eventually, though "don't touch a running system" applies.

The original gofmt code is from the Emacs 22 days, so it's possible that the insert-file-contents functionality was added later. I haven't checked that yet.

**Comment by aaronjensen** [comment]
Ok, great, thank you for responding--I just wanted to make sure I wasn't wading into some known broken territory. 

FWIW, there isn't a measurable performance difference, at least on my fast machine w/ SSD, so the benefit for me was only in code simplification and reduction. 

I'll close this out since there's not really an issue here.

**Comment by aaronjensen** [comment]
Looks like it was added prior to Emacs 19.34, so it's probably pretty solid by now. https://github.com/emacs-mirror/emacs/commit/3d0387c0f3be8e915aef9c5733be5bcec5f8924c

**Comment by dominikh** [comment]
Judging by a cursory reading of the implementation (http://sprunge.us/MTfJ), it will only work fine in some cases, as it only preserves the leading and trailing unchanged text, but will replace everything in the middle. This will likely not maintain point in as many situations as our current solution, which is granular down to the line.

**Comment by aaronjensen** [comment]
Interesting. From my experiments, it looks like the line the point is on is maintained in all the cases I try out, but it does move the point a few characters to the left, which is annoying.

**Comment by dominikh** [comment]
Point is a single integer offset, so it maintaining the line is just accidental, because the character offsets didn't move enough. It moving to the left is very much indicative of the underlying problem. With the diff approach, you only risk losing point if the line you're on has to be reformatted. With insert-file-contents, point will drift further and further the more changes have to be made.

**Comment by aaronjensen** [comment]
Ok, that makes sense. Looks like I'll go back to the diff method 😄 Thank you for your help.
